"""Narrow application contracts for local archive persistence and retained raw mail.

The records are immutable snapshots to callers; implementations own transactions.
"""

from __future__ import annotations

from collections.abc import Callable, Iterable, Mapping
from contextlib import AbstractContextManager
from datetime import datetime
from pathlib import Path
from typing import Any, Protocol

from mailarchive.domain.configuration import Settings
from mailarchive.domain.source_identity import MailTarget

Record = Mapping[str, Any]


class ConfigurationPort(Protocol):
    def prepare_run_settings(self, settings: Settings) -> int: ...


class DiscoveryPort(Protocol):
    def baseline_message(self, source_id: str, message_key: str) -> None: ...
    def cancel_intake(self, intake_id: str) -> None: ...
    def intake_operation_id(self, intake_id: str) -> str | None: ...
    def discard_pending(
        self,
        source_id: str,
        scope_key: str,
        remote_ids: set[str],
        *,
        run_id: str,
        processing_namespace: str,
    ) -> int: ...
    def finish_scope(
        self,
        source_id: str,
        scope_key: str,
        processing_namespace: str,
        synchronization_namespace: str,
        cursor: str,
    ) -> None: ...
    def intake_retry_deferred(self, source_id: str, message_key: str) -> bool: ...
    def intake_snapshot(self, intake_id: str) -> Settings: ...
    def mark_filtered(self, intake_id: str, *, received_at: str, received_origin: str) -> None: ...
    def mark_intake_error(
        self,
        intake_id: str,
        error: str,
        *,
        received_at: str | None = None,
        received_origin: str | None = None,
    ) -> bool: ...
    def mark_unmatched(
        self,
        intake_id: str,
        *,
        received_at: str,
        received_origin: str,
        sender_at: str | None,
        subject: str,
    ) -> None: ...
    def pause_scope(
        self,
        source_id: str,
        scope_key: str,
        error: str,
        *,
        processing_namespace: str | None = None,
    ) -> None: ...
    def pause_intake_scope(self, intake_id: str, error: str) -> None: ...
    def pending_automatic_intakes(
        self,
        *,
        due_only: bool = False,
        at: datetime | None = None,
        excluded_source_ids: frozenset[str] = frozenset(),
    ) -> list[Record]: ...
    def pending_rechecks(
        self,
        source_id: str,
        scope_key: str,
        *,
        force_retry: bool = False,
        at: datetime | None = None,
    ) -> set[str]: ...
    def prepare_scope_discovery(
        self, source_id: str, scope_keys: set[str], *, settings: Settings | None = None
    ) -> None: ...
    def record_scope_check_error(self, source_id: str, scope_key: str, error: str) -> None: ...
    def reject_intake(
        self,
        intake_id: str,
        error: str,
        *,
        received_at: str | None = None,
        received_origin: str | None = None,
    ) -> None: ...
    def release_intake(self, intake_id: str, status: str = "filtered") -> None: ...
    def reserve(
        self,
        source_id: str,
        message_key: str,
        run_id: str,
        *,
        automatic: bool,
        scope_key: str = "",
        remote_id: str = "",
        force_retry: bool = False,
    ) -> str | None:
        """Reserve work, or defer a conflicting unfinished owner for discovery replay."""
        ...

    def reset_scope_baseline(self, source_id: str, scope_key: str) -> int: ...
    def scope(self, source_id: str, scope_key: str) -> Record | None: ...
    def retained_imap_namespaces(self, target: MailTarget) -> frozenset[str]: ...
    def unresolved_intakes(self, run_id: str) -> list[Record]: ...


class OperationPort(Protocol):
    def cancel_run(self, run_id: str) -> None: ...
    def can_retry_manual_operation(self, operation_id: str) -> bool: ...
    def claim_manual_operation(self, operation_id: str) -> bool: ...
    def create_manual_operation(
        self, settings: Settings, source_ids: list[str], rule_id: str, selection: dict[str, Any]
    ) -> str: ...
    def finalize_stop_manual_operation(self, operation_id: str) -> None: ...
    def finish_manual_operation(self, operation_id: str, error: str | None = None) -> None: ...
    def finish_run(self, run_id: str, *, error: str | None = None) -> None: ...
    def incomplete_manual_runs(self) -> list[Record]: ...
    def interrupt_queued_manual_operations(self) -> None: ...
    def interrupt_run(
        self, run_id: str, reason: str = "Mail processing was interrupted."
    ) -> None: ...
    def manual_open_plans(self, operation_id: str) -> list[Record]: ...
    def manual_operation(self, operation_id: str) -> Record | None: ...
    def manual_operation_accepts_outputs(self, operation_id: str) -> bool: ...
    def manual_operation_accepts_work(self, operation_id: str) -> bool: ...
    def manual_run_for_source(self, operation_id: str, source_id: str) -> Record | None: ...
    def mark_operation_source(
        self, operation_id: str, source_id: str, status: str, error: str | None = None
    ) -> None: ...
    def plan_operation_active(self, plan_id: str, *, explicit: bool = False) -> bool: ...
    def range_target_checkpoint(self, run_id: str, scope_key: str) -> dict[str, object]: ...
    def request_stop_manual_operation(self, operation_id: str) -> bool: ...
    def restart_run(self, run_id: str) -> None: ...
    def run_operation_id(self, run_id: str) -> str | None: ...
    def run_settings_snapshot(self, run_id: str) -> Settings: ...
    def run_status(self, run_id: str) -> str | None: ...
    def start_run(
        self,
        source_id: str,
        kind: str,
        selection: dict[str, Any],
        settings: Settings,
        config_revision: int,
        operation_id: str | None = None,
    ) -> str: ...
    def update_range_target_checkpoint(
        self,
        run_id: str,
        scope_key: str,
        namespace: str,
        token: str | None,
        complete: bool,
        *,
        force: bool = False,
    ) -> bool: ...


class DeliveryPort(Protocol):
    def abort_plan(self, plan_id: str) -> None: ...
    def accept_plan(
        self,
        intake_id: str,
        raw_path: Path,
        raw_hash: str,
        received_at: str,
        received_origin: str,
        sender_at: str | None,
        subject: str,
        rule_json: str,
    ) -> str: ...
    def add_output(
        self,
        plan_id: str,
        source_id: str,
        message_key: str,
        artifact_key: str,
        digest: str,
        requested_path: str,
        final_path: str,
        target_id: str,
        *,
        status: str = "pending",
    ) -> int: ...
    def auto_resumable_plans(
        self, *, excluded_source_ids: frozenset[str] = frozenset(), force: bool = False
    ) -> list[Record]: ...
    def automatic_work_sources(self) -> list[Record]: ...
    def automatic_work_due(
        self,
        at: datetime | None = None,
        *,
        excluded_source_ids: frozenset[str] = frozenset(),
        paused_intake_ids: frozenset[str] = frozenset(),
    ) -> bool: ...
    def finish_plan_if_complete(self, plan_id: str) -> bool: ...
    def mark_target_no_output(self, plan_id: str, target_id: str) -> None: ...
    def open_plans(self) -> list[Record]: ...
    def output_done(
        self, output_id: int, plan: Record, *, started_at: str | None = None
    ) -> None: ...
    def output_error(
        self, output_id: int, error: str, *, started_at: str | None = None
    ) -> None: ...
    def outputs(self, plan_id: str) -> list[Record]: ...
    def pause_plan(self, plan_id: str) -> None: ...
    def plan_targets(self, plan_id: str) -> list[Record]: ...
    def receipt(
        self, source_id: str, message_key: str, artifact_key: str, digest: str, requested_path: str
    ) -> Record | None: ...
    def record_plan_failure(self, plan_id: str, error: str) -> None: ...
    def refresh_target_statuses(self, plan_id: str) -> None: ...
    def reserved_output_path(self, path: str) -> bool: ...
    def resume_plan(self, plan_id: str) -> None: ...
    def set_output_path(self, output_id: int, final_path: str) -> None: ...
    def set_plan_error(self, plan_id: str, error: str | None) -> None: ...
    def work_plans(self) -> list[Record]: ...


class SpoolPort(Protocol):
    def stage(self, chunks: Iterable[bytes]) -> tuple[Path, str]: ...
    def read(self, path: Path, max_bytes: int) -> bytes: ...
    def discard(self, path: Path) -> None: ...


class OutputFilesPort(Protocol):
    def filename_limit(self, directory: Path) -> int: ...
    def occupied(self, path: Path) -> bool: ...
    def matches(self, path: Path, expected_digest: str, size: int) -> bool: ...
    def publish(self, path: Path, content: bytes) -> None: ...


PlanExecution = Callable[[str], AbstractContextManager[None]]
